// <auto-generated />
using System;
using Examen_Parcial_1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Examen_Parcial_1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201001004630_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Examen_Parcial_1.Models.NCFAutorizados", b =>
                {
                    b.Property<int>("NcfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Limite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reorden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Secuencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoNcfId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Vence")
                        .HasColumnType("TEXT");

                    b.HasKey("NcfId");

                    b.ToTable("NCFAutorizados");
                });
#pragma warning restore 612, 618
        }
    }
}
